[tool.poetry]
name = "dsapa"
version = "0.1.0"
description = "Data Structures, Algorithms, Patterns and Architectures"
authors = ["Andrew Tanner <drewnix@drewnix.dev>"]

[tool.poetry.dependencies]
python = "^3.9"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
